---
- hosts: all
  tasks:
  - name: Common | Install packages
    become: true
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - unzip

  - name: Docker | Add an apt signing key for Docker
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Docker | Add apt repository for stable version
    become: true
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Docker | Install docker and its dependecies
    become: true
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io

  - name: Docker | Add vagrant user to docker group
    become: true
    user:
      name: vagrant
      group: docker

  - name: Kubernetes | Add an apt signing key for Kubernetes
    become: true
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    become: true
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Kubernetes | Install Kubernetes binaries
    become: true
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl
    
  - name: Minikube | Download Minikube
    become: true
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      dest: /home/vagrant

  - name: Minikube | Install Minikube
    become: true
    command: install minikube-linux-amd64 /usr/local/bin/minikube

  - name: Minikube | Start Minikube (This may take a while!)
    command: minikube start

  - name: Hello World | Download project files from github
    get_url:
      url: https://github.com/martinwrightgithub/docker-helloworld/archive/refs/heads/master.zip
      dest: /tmp

  - name: Hello World | unzip project files
    unarchive:
      src: /tmp/docker-helloworld-master.zip
      dest: /home/vagrant/
      remote_src: yes

  - name: Hello World | kubectl apply docker-helloworld
    command: kubectl apply -f /home/vagrant/docker-helloworld-master/deployment.yml
  
  - name: Hello World | kubenetes start helloworld service
    command: minikube service helloworld
